BeanBag/Models/AIModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BeanBag.Models
{
    public class AIModel
    {
        [Key]
        public Guid Id { get; set; }

        [StringLength(100, ErrorMessage = "AI Model name length can't be more than 100.")]
        public string name { get; set; }

        public DateTime dateCreated { get; set; }

        public string description { get; set; }

        public int? imageCount { get; set; }

        public string tenantId { get; set; }
    }
}

BeanBag/Controllers/AIModelController.cs
using BeanBag.Models;
using BeanBag.Models.Helper_Models;
using BeanBag.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Azure.CognitiveServices.Vision.CustomVision.Training.Models;
using Microsoft.Identity.Web;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace BeanBag.Controllers
{
    /* This controller is used to send and retrieve data to the dashboard
       view using AI Model and Blob Service functions. */
    public class AiModelController : Controller
    {
        // Global variables needed for calling the service classes.
        private readonly IAIService _aIService;
        private readonly IBlobStorageService _blobService;
        private readonly ITenantService _tenantService;
        private readonly IPaymentService _paymentService;
        
        // Constructor
        public AiModelController(IAIService aIService, IBlobStorageService blobService,
            IPaymentService paymentService, ITenantService tenantService)
        {
            _aIService = aIService;
            _blobService = blobService;
            _tenantService = tenantService;
            _paymentService = paymentService;

        }

        /* This function adds a page parameter, a current sort order parameter, and a current filter
         parameter to the method signature and returns a view model with pagination to return an AI model list. */
        public IActionResult Index(string sortOrder, string currentFilter, string searchString, int? page,
            DateTime from, DateTime to)
        {
            if(User.Identity is {IsAuthenticated: true})
            {
                
                 //A ViewBag property provides the view with the current sort order, because this must be included in 
                 //  the paging links in order to keep the sort order the same while paging
                ViewBag.CurrentSort = sortOrder;
                ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
                List<AIModel> modelList;

                //ViewBag.CurrentFilter, provides the view with the current filter string.
                //the search string is changed when a value is entered in the text box and the submit
                //button is pressed. In that case, the searchString parameter is not null.
                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }

                ViewBag.CurrentFilter = searchString;

                string tenantId = _tenantService.GetCurrentTenant(User.GetObjectId()).TenantId;

                var model = from s in _aIService.getAllModels(tenantId) select s;
            
                //Search and match data, if search string is not null or empty
                if (!String.IsNullOrEmpty(searchString))
                {
                    model = model.Where(s => s.name.Contains(searchString));
                }
                switch (sortOrder)
                {
                    case "name_desc":
                        modelList = model.OrderByDescending(s => s.name).ToList();
                        break;
                 
                    default:
                        modelList = model.OrderBy(s => s.name).ToList();
                        break;
                }
                
                //TO DO: Date sorting --- need to add sorting once date created to DB 
                /*     if (sortOrder == "date")
                {
                    modelList =( model.Where(t => t.createdDate > from && t.createdDate < to)).ToList();

                }*/
                
                //indicates the size of list
                int pageSize = 3;
            
                //set page to one is there is no value, ??  is called the null-coalescing operator.
                int pageNumber = (page ?? 1);
            
                //Initialise data and models to be returned to the view.
                AIModel mod = new AIModel();
                Pagination viewModel = new Pagination();
                IPagedList<AIModel> pagedList = modelList.ToPagedList(pageNumber, pageSize);
            
                viewModel.AiModel = mod;
                viewModel.PagedListModels = pagedList;
                @ViewBag.totalModels = _aIService.getAllModels(tenantId).Count;

                //Checking to see if the tenant is allowed to create more AI Models
                Tenant tenant = _tenantService.GetCurrentTenant(User.GetObjectId());

                List<AIModel> models = _aIService.getAllModels(tenantId);

                if(tenant.TenantSubscription == "Free")
                {
                    if (models.Count == 0)
                        ViewBag.createNewModels = true;
                    else
                        ViewBag.createNewModels = false;
                }
                else if(tenant.TenantSubscription == "Standard")
                {
                    if (models.Count < 3)
                        ViewBag.createNewModels = true;
                    else
                        ViewBag.createNewModels = false;
                }
                else if(tenant.TenantSubscription == "Premium")
                {
                    if (models.Count < 20)
                        ViewBag.createNewModels = true;
                    else
                        ViewBag.createNewModels = false;
                }
                
                //Subscription Expired 
                @ViewBag.SubscriptionExpired = false;
                if (_tenantService.GetCurrentTenant(User.GetObjectId()).TenantSubscription != "Free")
                {
                    var transaction =
                        _paymentService.GetPaidSubscription(_tenantService.GetCurrentTenant(User.GetObjectId()).TenantId);
                    if (transaction.EndDate <= DateTime.Now)
                    {
                        @ViewBag.SubscriptionExpired = true;
                    }
                }


                return View(viewModel);
            }
            else
            {
                return LocalRedirect("/");
            }
        }
        
         /* This function adds a page parameter, a current sort order parameter, and a current filter parameter
          to the method signature and returns a view model with pagination to return an AI model version list. */
        public IActionResult ModelVersions(Guid projectId, string sortOrder, string currentFilter, 
            string searchString, int? page,DateTime from, DateTime to)
        {
            if(User.Identity is {IsAuthenticated: true})
            {
                
                 //A ViewBag property provides the view with the current sort order, because this must be included in 
                 //  the paging links in order to keep the sort order the same while paging
                ViewBag.CurrentSort = sortOrder;
                ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
                List<AIModelVersions> modelList;

            
         
                //ViewBag.CurrentFilter, provides the view with the current filter string.
                //the search string is changed when a value is entered in the text box and the submit button is
                //pressed. In that case, the searchString parameter is not null.
                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }

                ViewBag.CurrentFilter = searchString;

                var model = from s in _aIService.getProjectIterations(projectId) 
                    select s;
            
                    //Search and match data, if search string is not null or empty
                    if (!String.IsNullOrEmpty(searchString))
                    {
                        model = model.Where(s => s.Name.Contains(searchString));
                    }
                    switch (sortOrder)
                    {
                        case "name_desc":
                            modelList = model.OrderByDescending(s => s.Name).ToList();
                            break;
                 
                        default:
                            modelList = model.OrderBy(s => s.Name).ToList();
                            break;
                    }

                    //TO DO: Date sorting --- need to add date created to DB 
                    /*     if (sortOrder == "date")
                    {
                        modelList =( model.Where(t => t.createdDate > from && t.createdDate < to)).ToList();
                    }*/
                
                //indicates the size of list
                int pageSize = 5;
            
                //set page to one is there is no value, ??  is called the null-coalescing operator.
                int pageNumber = (page ?? 1);
            
                //Setting models to be returned to the view
                AIModelVersions mod = new AIModelVersions();
                Pagination viewModel = new Pagination();
                IPagedList<AIModelVersions> pagedList = modelList.ToPagedList(pageNumber, pageSize);
            
          
                viewModel.PagedListVersions = pagedList;
                @ViewBag.totalModels = _aIService.getProjectIterations(projectId).Count;
                ViewBag.projectId = projectId;

                ViewBag.recommendations = _aIService.AIModelRecommendations(projectId); ;
                ViewBag.modelTags = _aIService.getModelTags(projectId);

                //IList<Tag> tags = _aIService.getModelTags(projectId);
                //foreach(var t in tags)
                //    t.ima

BeanBag/Views/AIModel/CompareVersions.cshtml
<link href="~/lib/bootstrap/dist/css/" rel="stylesheet" />
<link rel="stylesheet" href="~/css/circleProgressBar.css" />
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

<section class="page-content" xmlns="http://www.w3.org/1999/html">

    <section class="ml-3">
        <a asp-action="Index" asp-controller="AiModel" class="btn "><i class="fas fa-chevron-left text-color"></i></a>

        <span class="  md-2 text-secondary ">
            &nbsp; Compare AI Model Versions 
        </span>

    </section>
    <hr>

    <div class="dashboard-wrapper">
        <div class="container-fluid dashboard-content helloUser">
         
            <div class="row">
                
               
                
               <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 pt-4 pb-2">
                              <div >
                
                        <div class="card shadow  mb-3 bg-body rounded-lg" id="CategoryID">
                            <h5 class="text-secondary p-4 pb-0"> Compare AI Model Versions</h5>
                            <div class="card-body p-4 pt-1">
                                <p> Compare different versions of a model to determine the best Model version to use for your item cateloging process.</p>
                                    
                            </div>  </div>  </div>  </div>
                
                
                
                <div class="col-md-6">    <b>Select a Model Version &nbsp;</b> 
                    <div>
                          <span class="col-md-3 ml-auto ">
                          
                     
                            <select class="form-control shadow-sm bg-body rounded-lg col-md-3" id="dropDown1" asp-items="@ViewBag.iterationDropDown"></select>
                        </span>
                    </div>
                                        <div class="card shadow mb-3 bg-body rounded-lg" id="CategoryId">
                                            <div class="card-body p-3">
                                                <div class="table-responsive">
                                                    <table class="table text-center">
                                                        <thead class="bg-light">
                                                        <tr>
                                                            <th class="border-0">Tag</th>
                                                            <th class="border-0">Precision &nbsp;<i class="fas fa-info-circle" title="Precision"></i></th>
                                                            <th class="border-0">Recall&nbsp;<i class="fas fa-info-circle" title="Recall"></i></th>
                                                            <th class="border-0">A.P.&nbsp;<i class="fas fa-info-circle" title="A.P"></i></th>
                                                            <th class="border-0">Image Count</th>
                                                        </tr>
                                                        </thead>
                                                        <tbody id="version1Compare">
                                                        </tbody>
                                                    </table>
                                                </div>
                                                <br>
                                                <section id="progress bars version1Compare">

                                                </section>
                                            </div>
                                        </div>
                                    </div>
                <div class="col-md-6">
                         <b>Select a Model Version &nbsp;</b>
                                                         
                    <div>

                        <span class="col-md-3 ml-auto">
                            <select class="form-control shadow-sm bg-body rounded-lg col-md-3" id="dropDown2" asp-items="@ViewBag.iterationDropDown"></select>
                        </span>
                    </div>
                    <div class="card shadow mb-3 bg-body rounded-lg" id="CategoryId">
                        <div class="card-body  p-3">
                            <div class="table-responsive">
                                <table class="table text-center">
                                    <thead class="bg-light">
                                    <tr>
                                        <th class="border-0">Tag</th>
                                        <th class="border-0">Precision&nbsp;<i class="fas fa-info-circle" title="How likely will the AI model version be right when predicting this tag"></i></th>
                                        <th class="border-0">Recall&nbsp;<i class="fas fa-info-circle" title="How likely did the AI model version correctly find the tag in the prediction"></i></th>
                                        <th class="border-0">A.P.&nbsp;<i class="fas fa-info-circle" title="Overall average of precision and recall values"></i></th>
                                        <th class="border-0">Image Count</th>
                                    </tr>
                                    </thead>
                                    <tbody id="version2Compare" >
                                    </tbody>
                                </table>
                            </div>
                            <br>
                            <section id="progress bars version2Compare">

                            </section>
                        </div>
                    </div>
                </div>
                                </div>
        </div>
    </div>

</section>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script type="text/javascript">


    $(document).ready(function () {
        
    });

    @* VERSION 1 DROP DOWN *@
    $('#dropDown1').change(function () {
        $("#version1Compare").html('<i class="fa fa-spinner fa-spin" style="font-size:24px"></i>');

        var value = $('#dropDown1').val();

        var formData = new FormData();
        formData.append("iterationId", value);

        $.ajax({
            type: 'POST',
            url: '@Url.Action("GetVersionCompare")',
            contentType: false,
            processData: false,
            data: formData
        }).done(function (response) {

            var returnString = "";

            var performances = response.performances;

            for (var i = 0; i < performances.length; i++) {
                returnString += "<tr>";
                returnString += "<td>" + performances[i].tagName + "</td>";
                returnString += "<td>" + performances[i].precision + "%</td>";
                returnString += "<td>" + performances[i].recall + "%</td>";
                returnString += "<td>" + performances[i].averagePrecision + "%</td>";
                returnString += "<td>" + performances[i].imageCount + "</td>";
                returnString += "</tr>"
            }

            $("#version1Compare").html(returnString);

            console.log("version 1 done");

        });

    });

    @* VERSION 2 DROP DOWN *@
    $('#dropDown2').change(function () {
    $("#version2Compare").html('<i class="fa fa-spinner fa-spin" style="font-size:24px"></i>');
     var value = $('#dropDown2').val();

        var formData = new FormData();
        formData.append("iterationId", value);

        $.ajax({
            type: 'POST',
            url: '@Url.Action("GetVersionCompare")',
            contentType: false,
            processData: false,
            data: formData
        }).done(function (response) {

            var returnString = "";

            var performances = response.performances;

            for (var i = 0; i < performances.length; i++) {
                returnString += "<tr>";
                returnString += "<td>" + performances[i].tagName + "</td>";
                returnString += "<td>" + performances[i].precision + "%</td>";
                returnString += "<td>" + performances[i].recall + "%</td>";
                returnString += "<td>" + performances[i].averagePrecision + "%</td>";
                returnString += "<td>" + performances[i].imageCount + "</td>";
                returnString += "</tr>"
            }

            $("#version2Compare").html(returnString);

            console.log("version 2 done");
        });
    });

</script>

BeanBag/Views/AIModel/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<section class="inventory d-flex justify-content-center">
    <form method="post" asp-controller="AIModel" asp-action="Create" class="createForm">
        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="form-group row">
            <h3>Create inventory</h3>
        </div>
        <div class="form-group row">
            <label>Model Name</label>
            <input name="modelName" class="form-control" />
        </div>
        <input type="submit" class="btn btn-1" value="Next" /> <!--create button-->

        <a asp-controller="Home" asp-action="Index" class="btn btn-2">Back</a> <!--Back-->
    </form>
</section>

BeanBag/Views/AIModel/DeleteAIModel.cshtml
@model AIModel
@using Microsoft.Extensions.Options
@using Microsoft.Identity.Web
@inject IOptions<MicrosoftIdentityOptions> _azureAdb2COptions
@{
    Layout = null;
}

<div class="modal-body">
    <div class="form-group">
        <div class="text-muted">Are you sure you want to delete this AI Model ?</div>
       
     
               <div class="stats mt-2 pt-4">
                    <div class="d-flex justify-content-between p-price"><span>Name</span><span>@Model.name</span></div>
                    <div class="d-flex justify-content-between p-price"><span>ID</span><span>@Model.Id</span></div>
                    <div class="d-flex justify-content-between p-price"><span>Date Created</span><span>@Model.dateCreated</span></div>
                    <div class="d-flex justify-content-between p-price"><span>Description</span><span>@Model.description</span></div>
                </div>
        <input asp-for="Id" hidden name="projectId"/>
        <div asp-validation-summary="All" class="text-danger"></div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
    <input type="submit" class="btn btn-3" value="Delete" />
</div>

BeanBag/Views/AIModel/DeleteTag.cshtml
@model BeanBag.Models.Helper_Models.ModelTag
@using Microsoft.Extensions.Options
@using Microsoft.Identity.Web
@inject IOptions<MicrosoftIdentityOptions> _azureAdb2COptions
@{
    Layout = null;
}

<div class="modal-body">
    <div class="form-group">
        <h6 class="text-muted">Are you sure you want to delete this AI Model tag ?</h6>
        <hr>
        <div class="stats mt-2">
            <div class="d-flex justify-content-around-between p-price"><span>ID</span><span>@Model.Id</span></div>
            <div class="d-flex justify-content-around-between p-price"><span>Tag</span><span>@Model.name</span></div>
            <div class="d-flex justify-content-around-between p-price"><span>Image Count</span><span>@Model.imageCount</span></div>
        </div>
        <input asp-for="Id" hidden/>
        <input asp-for="projectId" hidden />
        <input asp-for="imageCount" hidden />
        <div asp-validation-summary="All" class="text-danger"></div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
    <input type="submit" class="btn btn-3" value="Delete" asp-controller="AIModel" asp-action="DeleteTag"/>
</div>

BeanBag/Views/AIModel/EditAIModel.cshtml
@model AIModel
@using Microsoft.Extensions.Options
@using Microsoft.Identity.Web
@inject IOptions<MicrosoftIdentityOptions> _azureAdb2COptions
@{
    Layout = null;
}


<!--Edit inventory inner card popup -->
<div class="modal-body">

    <div class="form-group ">
        <input asp-for="Id" name="projectId" hidden />

        <label asp-for="name" class="col-form-label">AI Model Name *</label> <!--Inventory Name-->
        <input asp-for="name" name="projectName" class="form-control" /> <!--input box-->
        <label asp-for="description" class="col-form-label">Description *</label> <!--Description-->
        <input asp-for="description" class="form-control" /> <!--input box-->
    </div>
    <div asp-validation-summary="All" class="text-danger"></div>
</div>

<div class="modal-footer ">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <input type="submit" class="btn btn-3" value="Save Changes" /> <!--create button-->
</div>

BeanBag/Views/AIModel/EditVersion.cshtml
@model AIModelVersions
@using Microsoft.Extensions.Options
@using Microsoft.Identity.Web
@inject IOptions<MicrosoftIdentityOptions> _azureAdb2COptions
@{
    Layout = null;
}


<!--Edit inventory inner card popup -->
<div class="modal-body">

    <div class="form-group ">
        <input asp-for="Id" hidden />
        <input asp-for="projectId" hidden />

        <label asp-for="description" class="col-form-label">Description *</label> <!--Description-->
        <input asp-for="description" class="form-control" /> <!--input box-->
    </div>
    <div asp-validation-summary="All" class="text-danger"></div>
</div>

<div class="modal-footer ">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <input type="submit" class="btn btn-3" value="Save Changes" /> <!--create button-->
</div>

BeanBag/Views/AIModel/ViewPerformance.cshtml
@model List<BeanBag.Models.Helper_Models.AIModelVersionTagPerformance>
@using Microsoft.Extensions.Options
@using Microsoft.Identity.Web
@inject IOptions<MicrosoftIdentityOptions> _azureAdb2COptions
@{
    Layout = null;
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="modal-body">
    <div class="form-group">
        <h6 class="text-muted pb-2"> The performance metrics for the model version is shown below.</h6>
       
        <div class="stats mt-2">
            <table class="table text-center">
                <thead>
                    <tr>
                        <th scope="col">Tag</th>
                        <th scope="col">Precision</th>
                        <th scope="col">Recall</th>
                        <th scope="col">A.P.</th>
                        <th scope="col">Image Count</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var t in Model)
                    {
                    <tr>
                        <th scope="row">@t.tagName</th>
                        <th scope="row">@t.precision.ToString("#.##")%</th>
                        <th scope="row">@t.recall.ToString("#.##")%</th>
                        <th scope="row">@t.averagePrecision.Value.ToString("#.##")%</th>
                        <th scope="row">@t.imageCount</th>
                    </tr>
                    }
                </tbody>
            </table>
            
        </div>
    </div>
</div>

BeanBag/Views/AIModel/_DeleteTag.cshtml
@addTagHelper *, Microsoft.AspNetCore.TagHelpers

<div class="modal fade" id="exampleModal4" tabindex="-1" role="dialog" aria-labelledby="exampleModalTitle4" aria-hidden="true">
    <div class="modal-dialog modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalTitle4">Delete AI Model Tag </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" asp-controller="AIModel" asp-action="DeleteTag" class="data"></form>
        </div>
    </div>
</div>

BeanBag/Views/AIModel/_DeleteVersion.cshtml
@addTagHelper *, Microsoft.AspNetCore.TagHelpers

<div class="modal fade" id="exampleModal4" tabindex="-1" role="dialog" aria-labelledby="exampleModalTitle4" aria-hidden="true">
    <div class="modal-dialog modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalTitle4">Delete AI Model Version </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" asp-controller="AIModel" asp-action="DeleteVersionPost" class="data"></form>
        </div>
    </div>
</div>

BeanBag/Views/AIModel/_EditAIModel.cshtml
@addTagHelper *, Microsoft.AspNetCore.TagHelpers

<div class="modal fade" id="exampleModal3" tabindex="-1" role="dialog" aria-labelledby="exampleModalTitle3" aria-hidden="true">
    <div class="modal-dialog modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalTitle3">Edit AI Model</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" asp-controller="AIModel" asp-action="EditAiModelPost" class="data"></form>
        </div>
    </div>
</div>

BeanBag/Views/AIModel/_ViewPerformance.cshtml
@addTagHelper *, Microsoft.AspNetCore.TagHelpers

<div class="modal fade" id="viewVersionPerformance" tabindex="-1" role="dialog" aria-labelledby="viewVersionPerformance" aria-hidden="true">
    <div class="modal-dialog modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="viewVersionPerformances">Performance Metrics@*<i class="fas fa-trash"> </i>*@</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
             <form method="get" asp-controller="AIModel" asp-action="ViewPerformance" asp-route-Id="@ViewBag.iterationId" class="data"></form>
       <a asp-controller="AiModel" asp-action="CompareVersions" asp-route-selectedVersion="@ViewBag.iterationId" class="btn btn-3 shadow-sm bg-body rounded">Compare Versions &nbsp; <i class="fa fa-exchange" aria-hidden="true"></i></a>
      
            </div>
    </div>
</div>