BeanBag/Controllers/TenantSettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using BeanBag.Database;
using BeanBag.Models;
using BeanBag.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Identity.Web;
using X.PagedList;
using MimeKit;
using SmtpClient = MailKit.Net.Smtp.SmtpClient;

namespace BeanBag.Controllers
{
    public class TenantSettingsController : Controller
    {
        
        // Global variables needed for calling the service classes.
        private readonly ITenantService _tenantService;
        private readonly TenantDbContext _tenantDbContext;
        private readonly IConfiguration _configuration;
        private readonly IPaymentService _paymentService;
        private readonly string _from;
        private readonly string _pswd;

        // Constructor.
        public TenantSettingsController(ITenantService tenantService, TenantDbContext tenantDbContext, IConfiguration configuration, IPaymentService pay)
        {
            _tenantService = tenantService;
            _tenantDbContext = tenantDbContext;
            _configuration = configuration;
            _paymentService = pay;

            _from = configuration.GetValue<String>("EmailDetails:Username");
            _pswd = configuration.GetValue<String>("EmailDetails:Password");
        }

        /* Provides a list of users under the currently signed in tenant */
        [AllowAnonymous]
        public IActionResult Index(string sortOrder, string currentFilter, string searchString,
            int? page)
        {
            if(User.Identity is {IsAuthenticated: true})
            {
                
             //A ViewBag property provides the view with the current sort order, because this must be included in 
             //the paging links in order to keep the sort order the same while paging
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            IEnumerable<TenantUser> modelList;

            //ViewBag.CurrentFilter, provides the view with the current filter string.
            //he search string is changed when a value is entered in the text box and the submit button is pressed. In that case, the searchString parameter is not null.
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            var model = from s in _tenantService.GetUserList(User.GetObjectId())
                select s;
                //Search and match data, if search string is not null or empty
                if (!String.IsNullOrEmpty(searchString))
                {
                    model = model.Where(s => s.UserName.Contains(searchString));
                }

                var users = model.ToList();
                switch (sortOrder)
                {
                    case "name_desc":
                        modelList = users.OrderByDescending(s => s.UserName).ToList();
                        break;
                 
                    default:
                        modelList = users.OrderBy(s => s.UserName).ToList();
                        break;
                }
                
            //indicates the size of list
            int pageSize = 5;
            //set page to one is there is no value, ??  is called the null-coalescing operator.
            int pageNumber = (page ?? 1);
            //return the Model data with paged

            TenantUser tenantUser = new TenantUser();
            Pagination viewModel = new Pagination();
            IPagedList<TenantUser> pagedList = modelList.ToPagedList(pageNumber, pageSize);

            viewModel.TenantUser = tenantUser;
            viewModel.PagedListTenantUsers = pagedList;
             @ViewBag.tenant =  _tenantService.GetCurrentTenant(User.GetObjectId());
            //Checking user role is in DB
            //CheckUserRole();
            @ViewBag.totalUsers = pagedList.Count;
            @ViewBag.subscription = _tenantService.GetCurrentTenant(User.GetObjectId()).TenantSubscription;
               
            //Subscription Expired 
            @ViewBag.SubscriptionExpired = false;
            if (_tenantService.GetCurrentTenant(User.GetObjectId()).TenantSubscription != "Free")
            {
                var transaction =
                    _paymentService.GetPaidSubscription(_tenantService.GetCurrentTenant(User.GetObjectId()).TenantId);
                if (transaction.EndDate <= DateTime.Now)
                {
                    @ViewBag.SubscriptionExpired = true;
                }
            }
            return View(viewModel);
            }
            else
            {
                return LocalRedirect("/");
            }
        }
        
        
        /* Allows admin user to edit the tenant details through pop-up form. Changes get saved to database. */
        [HttpPost]
        public IActionResult EditDetails(string tenantName, string tenantAddress, string tenantEmail, string tenantNumber)
        {
            if(User.Identity is {IsAuthenticated: true})
            {

                var tenant = _tenantService.GetCurrentTenant(User.GetObjectId());
                
                if(tenant!=null)
                {
                    _tenantService.EditTenantDetails(tenant.TenantId,tenantName,tenantAddress,tenantEmail,tenantNumber);
                    return RedirectToAction("Index");
                }
                else 
                {
                    return BadRequest();
                }  
                        
            }
            else
            {
                return LocalRedirect("/");
            }
        }
        
        /* Delete Get method. Passes user to be deleted to the Post method. */
        public IActionResult Delete(string userObjectId)
        {
            if (User.Identity is {IsAuthenticated: true})
            {

                if (userObjectId == null)
                {
                    return BadRequest();
                }
                
                var user = _tenantDbContext.TenantUser.Find(userObjectId);
                return View(user);
            }

            return LocalRedirect("/");
        }
        
        
        /* Edit Get method. Passes user role and user id to Post method. */
        public IActionResult Edit(string userId)
        {
            if (userId == null)
            {
                return BadRequest();
            }
            
            var user = _tenantDbContext.TenantUser.Find(userId);
            var role = _tenantService.GetUserRole(userId);
                
            return View(role,userId);
                
        }
        
        /* Post method for deleting a user. Receives user object id and deletes user from database. */
        [HttpPost]
        public IActionResult DeletePost(string userObjectId)
        {
            if (userObjectId == null)
            {
                return BadRequest();
            }
            
            //User cannot delete themselves
            if (userObjectId.Equals(User.GetObjectId()))
            {
                return BadRequest();
            }

            //Delete the user from database
            if (_tenantService.DeleteUser(userObjectId))
            {
                return RedirectToAction("Index");
            }

            return LocalRedirect("/");
        }
        
        /* Post method to edit the user role. This method receives the user id and the updated role from Edit. */
        [HttpPost]
        public IActionResult EditPost(string UserObjectId, string UserRole)
        {
            if (UserRole == null)
            {
                return BadRequest();
            }

            if (_tenantService.EditUserRole(UserObjectId,UserRole))
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        /* This function allows an admin to delete the tenant. Deleting a tenant deletes all the users of that
         tenant as well. */
        public IActionResult DeleteTenant()
        {
            //Get current tenant
            var tenant = _tenantService.GetCurrentTenant(User.GetObjectId());

            if (tenant == null)
            {
                return BadRequest();
            }
            
            //Delete the tenant 
            _tenantService.DeleteTenant(User.GetObjectId());
            
            //Redirect back to landing page
            return RedirectToPage("LandingPage");
        }

        /* This function allows an admin user to invite a new user to join the tenant.
         The user email will be entered - user receives a random code and link to complete sign up process. */
        [HttpPost]
        public IActionResult InviteNewUser(string userEmail)
        {
            if (userEmail == null)
            {
                return BadRequest();
            }
            
            //Get current tenant
            var tenant = _tenantService.GetTenantName(_tenantService.GetUserTenantId(User.GetObjectId()));
            
            //Generate a code to send user
            var code = _tenantService.GetTenantCode(_tenantService.GetCurrentTenant(User.GetObjectId()).TenantId);
            
            
            //Link
            const string link = "https://beanbagpolaris.azurewebsites.net//LandingPage";

            var mimeMessage = new MimeMessage();
            
            //add sender
            mimeMessage.From.Add(new MailboxAddress("Bean Bag", _from));

            //add receiver
            mimeMessage.To.Add(MailboxAddress.Parse(userEmail));
            
            //add message subject
            mimeMessage.Subject = tenant + " Invitation";
            
            //message

BeanBag/Views/TenantSettings/Delete.cshtml
@model TenantUser
@using Microsoft.Extensions.Options
@using Microsoft.Identity.Web
@inject IOptions<MicrosoftIdentityOptions> _azureAdb2COptions
@{
    Layout = null;
}

<!--Delete inventory inner card popup -->
<div class="modal-body ">
    <div class="form-group">
        <div class="text-muted"> Are you sure that you want to delete this user? </div>
      
        <div class="stats mt-2 pt-4">
            <div class="d-flex justify-content-between p-price"><span>ID</span><span>@Model.UserTenantId</span></div>
            <div class="d-flex justify-content-between p-price"><span>Username</span><span>@Model.UserName</span></div>
            <div class="d-flex justify-content-between p-price"><span>UserRole</span><span>@if(@Model.UserRole=="A"){<p>Admin</p>}else{<p>User</p>}</span></div>
        </div>
        <input asp-for="UserObjectId" hidden/>

        <div asp-validation-summary="All" class="text-danger"></div>
    </div>
</div>
<div class="modal-footer ">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
    <input type="submit" class="btn btn-3" value="Delete"/> <!--create button-->
</div>

BeanBag/Views/TenantSettings/Edit.cshtml
@model TenantUser
@using Microsoft.Extensions.Options
@using Microsoft.Identity.Web
@inject IOptions<MicrosoftIdentityOptions> _azureAdb2COptions
@{
    Layout = null;
}

<!--Edit inventory inner card popup -->
<div class="modal-body">

    <div class="form-group ">
        <input asp-for="UserObjectId" hidden/>
        
        <label asp-for="UserRole">User</label><br>
        <input asp-for="UserRole" type="radio" id="user" name="userRole" value="User">
        
        <label asp-for="UserRole">Admin</label><br>
        <input asp-for="UserRole" type="radio" id="admin" name="userRole" value="Admin">

    </div>
    <div asp-validation-summary="All" class="text-danger"></div>
    
</div>

<div class="modal-footer ">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <input type="submit" class="btn btn-3" value="Save Changes"/> <!--create button-->
</div>

BeanBag/Views/TenantSettings/_Delete.cshtml
    @model Pagination
    @addTagHelper *, Microsoft.AspNetCore.TagHelpers
    
<!---Popup Form to delete user -->
<div class="modal fade" id="exampleModalDelete" tabindex="-1" role="dialog" aria-labelledby="exampleModalTitleDelete" aria-hidden="true">
    <div class="modal-dialog modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"  id="exampleModalTitleDelete">Delete User </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" asp-controller="TenantSettings" asp-action="DeletePost" class="data"></form>
        </div>
    </div>
</div>

BeanBag/Views/TenantSettings/_Edit.cshtml
<!---Popup Form to edit user -->
<div class="modal fade" id="exampleModalEdit" tabindex="-1" role="dialog" aria-labelledby="exampleModalTitleEdit" aria-hidden="true">
    <div class="modal-dialog modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"  id="exampleModalTitleEdit">Edit User</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" asp-controller="TenantSettings" asp-action="EditPost" class="data"></form>
        </div>
    </div>
</div>