BeanBag/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using BeanBag.Models;
using BeanBag.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Web;
using X.PagedList;

namespace BeanBag.Controllers
{
    // This controller sends and receives data to the paygate api and
    // calls functions in the payment service classes
    public class PaymentController : Controller
    {
        private readonly IPaymentService _paymentService;
        private readonly ITenantService _tenantService;
        
        // the company will have their own details , this is for test purposes.
        readonly string PayGateID = "10011072130"; 
        readonly string _payGateKey = "secret";

        // Constructor.
        public PaymentController(IPaymentService payment, ITenantService tenant)
        {
            _paymentService = payment;
            _tenantService = tenant;
        }
        
        // This function is the get request for the payment gateway and will accept the payment amount.
        public async Task<IActionResult> GetRequest(string email, string amount)
        {
            Console.WriteLine("Checking the user id getReq: " + User.GetObjectId());


            HttpClient http = new HttpClient();
            string reference = Guid.NewGuid().ToString();
            Dictionary<string, string> request = new()
            {
                {"PAYGATE_ID", PayGateID},
                {"REFERENCE", reference},
                {"AMOUNT", amount},
                {"CURRENCY", "ZAR"},
                // Return url to original payment page -- run in ngrok
                // ngrok http -host-header="localhost:44352"
                {"RETURN_URL",
                    "https://beanbagpolaris.azurewebsites.net/Payment/CompletePayment?amounts=" +
                               ""+amount+"&references="+reference},
                {"TRANSACTION_DATE", DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")},
                {"LOCALE", "en-za"},
                {"COUNTRY", "ZAF"},
                {"EMAIL", email}
            };
            
            request.Add("CHECKSUM", _paymentService.GetMd5Hash(request, _payGateKey));

            string requestString = _paymentService.ToUrlEncodedString(request);
            StringContent content = new StringContent(requestString,
                Encoding.UTF8, "application/x-www-form-urlencoded");
            HttpResponseMessage response
                = await http.PostAsync("https://secure.paygate.co.za/payweb3/initiate.trans", content);

            // if the request did not succeed, this line will make the program crash
            response.EnsureSuccessStatusCode();

            string responseContent = await response.Content.ReadAsStringAsync();

            Dictionary<string, string> results = _paymentService.ToDictionary(responseContent);

            if (results.Keys.Contains("ERROR"))
            {
                return Json(new
                {
                    success = false,
                    message = "An error occured while initiating your request"
                });
            }

            if (!_paymentService.VerifyMd5Hash(results, _payGateKey, results["CHECKSUM"]))
            {
                return Json(new
                {
                    success = false,
                    message = "MD5 verification failed"
                });
            }

            return Json(new
                {
                    success = true,
                    message = "Request completed successfully",
                    results
                });

        }

        // This function is used to complete the payment and return to the website.
        [HttpPost]
        public ActionResult CompletePayment(string amounts, string references)
        {
            Console.WriteLine("Checking the user id complete pay: " + User.GetObjectId());


            var responseContent = Request.Query.Concat(Request.Form);
            
            var results = responseContent.ToDictionary(x 
                => x.Key, x => x.Value);
    
            return  RedirectToAction("Complete", new { id = results["TRANSACTION_STATUS"] ,
                amount=amounts, payReqId=results["PAY_REQUEST_ID"] , reference=references});
        }

        //This function occurs after completing the payment, and presents a popup of the transaction status.
        public ActionResult Complete(int? id, string amount, string payReqId , string reference)
        {
            string status;
            switch (id.ToString())
            {
                case "-2":
                    status = "Unable to reconcile transaction";
                    break;
                case "-1":
                    status = "Checksum Error. The values have been altered";
                    break;
                case "0":
                    status = "Not Done";
                    break;
                case "1":
                    ViewBag.payReqId = payReqId;
                    ViewBag.reference = reference;

                    //Transaction Approved 
                    //Console.WriteLine("Checking the user id complete: " + User.GetObjectId());

                    //Determine the type of subscription
                    ViewBag.Subscription = amount.Equals("50000") ? "Standard" : "Premium";
                    ViewBag.UpdatedSubscription = false;

                    try
                    {
                        if(_tenantService.GetCurrentTenant(User.GetObjectId()).TenantId != null)
                        {
                            @ViewBag.UpdatedSubscription = true;
                        }
                    }
                    catch(Exception e)
                    {
                        if (e.ToString().Equals("User does not exist in the database.")) 
                        {
                            return View();
                        }
                    }

                    return View();

                case "2":
                    status = "Declined";
                    break;
                case "3":
                    status = "Cancelled";
                    break;
                case "4":
                    status = "User Cancelled";
                    break;
                default:
                    status = $"Unknown Status({ id })";
                    break;
            }

            TempData["Status"] = status;

            try 
            {
                if (_tenantService.GetCurrentTenant(User.GetObjectId()).TenantId != null)
                {
                    //Error popup
                    return RedirectToAction("Index", "Home");
                }
            }
            catch(Exception e)
            {
                if (e.ToString().Equals("User does not exist in the database."))
                {
                    //error popup
                    return RedirectToAction("Index", "Tenant");
                }
            }

            //error popup
            return RedirectToAction("Index", "Tenant");  
        }
        
        // This function returns the billing page where the tenant can view their transactions.
        public IActionResult Billing(string sortOrder, string currentFilter, string searchString,
            int? page,DateTime from, DateTime to, string subscription)
        {
            if(User.Identity is {IsAuthenticated: true})
            {
                
             //A ViewBag property provides the view with the current sort order, because this must be included in 
             //the paging links in order to keep the sort order the same while paging
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            List<Transactions> modelList;

            //ViewBag.CurrentFilter, provides the view with the current filter string.
            //he search string is changed when a value is entered in the text box and the submit button is pressed. In that case, the searchString parameter is not null.
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            
            var currentTenantId = _tenantService.GetCurrentTenant(User.GetObjectId()).TenantId;
           
            //transaction
            var model = from s in _paymentService.GetTransactions(currentTenantId)
                select s;
                //Search and match data, if search string is not null or empty
                if (!String.IsNullOrEmpty(searchString))
                {
                    model = model.Where(s => s.Reference.ToString().Contains(searchString));
                }

                var inventories = model.ToList();
                switch (sortOrder)
                {
                    case "name_desc":
                        modelList = inventories.OrderByDescending(s => s.StartDate).ToList();
                        break;
                 
                    default:
                        modelList = inventories.OrderBy(s => s.StartDate).ToList();
                        break;
                }

                //Date sorting
                if (sortOrder == "date")
                {
                    modelList =( inventories.Where(t => t.StartDate > from && t.StartDate < to)).ToList();
                }
                
            //indicates the size of list
            int pageSize = 5;
            //set page to one is there is no value, ??  is called the null-coalescing operator.
            int pageNumber = (page ?? 1);
            //return the Model data with paged

          
            Pagination viewModel = new Pagination();
            IPagedList<Transactions> pagedList = modelList.ToPagedList(pageNumber, pageSize);

BeanBag/Controllers/WelcomeController.cs
using System;
using BeanBag.Database;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using BeanBag.Services;
using Microsoft.Identity.Web;

namespace BeanBag.Controllers
{
    public class WelcomeController : Controller
    {

        private readonly ITenantService _tenantService;
        private readonly TenantDbContext _tenantDbContext;
        public WelcomeController(ITenantService tenantService, TenantDbContext context)
        {
            _tenantService = tenantService;
            _tenantDbContext = context;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            if (User.GetObjectId() == null)
            {
                throw new Exception("User ID is null");
            }
            else if (_tenantService.SearchUser(User.GetObjectId()))
            {
                //Redirect user to dashboard if they are already signed up
                return RedirectToAction("Index", "Home");
            }
            
            return View();
        }

        
        /* Receives invitation code and verifies if the code is correct.
         If correct the user is signed up and gets redirected to the dashboard */
        [HttpPost]
        public IActionResult VerifyCode(string code)
        {
            if (code == null)
            {
                return BadRequest();
            }

            //Verify the entered code
            if (_tenantService.VerifyCode(code))
            {
                //Code is verified, sign user up under tenant 
                var tenant = _tenantService.GetInvitationTenant(code);

                if (tenant == null)
                {
                    return BadRequest();
                }

                //Add user to the database
                if (_tenantService.SignUserUp(User.GetObjectId(), tenant.TenantId, User.GetDisplayName()))
                {
                   /* tenant.InviteCode = _tenantService.GenerateCode();
                    _tenantDbContext.SaveChanges(); */
                    return RedirectToAction("Index", "Home");
                }

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

    }
}

BeanBag/Views/Payment/Complete.cshtml
@{
   
    Layout = null;
}
<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Bootstrap CSS -->

	<link rel = "icon" href ="https://img.icons8.com/ios/50/ffffff/circled-b.png" type = "image/x-icon">
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta/css/bootstrap.min.css" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" rel="stylesheet">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link rel="stylesheet" href="~/css/dashboard.css" />
	<link rel="stylesheet" href="~/css/tenant.css" />
  
	<title> Pricing </title>

</head>


<style>
    .hidden {
        display: none;
    }

    li {
        list-style-type: none;
    }
 
</style>




<!--Nav-->
<nav class="navbar navbar-expand-md navbar-light">
	<a href="#" class="navbar-brand">Bean Bag</a>
	<button class="navbar-toggler ml-auto float-right mr-5" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	
	
	<div class="collapse navbar-collapse float-right ml-sm-auto"  id="navbarNav" >
		<ul class="navbar-nav ml-auto  pt-1">
				
			<li class="nav-item mr-5">

			

				<a class="nav-link  float-right " asp-area="MicrosoftIdentity" asp-controller="Welcome" asp-action="Index">
					Home
				</a>


			</li>
			
			<li class="nav-item  mr-5 ">		<a class="nav-link float-right" asp-area="MicrosoftIdentity" asp-controller="Tenant" asp-action="Index">
					Plans
				</a>
			</li>
			<li class="nav-item  mr-5 ">
				<a class="nav-link float-right" asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignOut">
					SignOut
				</a>
			</li>

		</ul>
		
	</div>
	<hr>
</nav>

<div class="container h-75 d-flex justify-content-center">
    <div class="pl-5 pr-5 my-auto pt-xl-3 text-center">    
	    <!--Successful Payment here-->
        	<h1> Payment was completed successfully <img alt="" width="50" src="https://img.icons8.com/color/48/000000/checked--v4.gif"/></h1>
	    
	    		@if (@ViewBag.UpdatedSubscription==false)
			    {
				    <h4 class="pb-2"> Start creating a new tenant now</h4>
				    <!-- Button trigger modal -->
				    <button class="btn btn-outline-light shadow-sm bg-body create rounded colors pt-2 "  data-toggle="modal" data-target="#exampleModal3"  id="btn-pay" >Create New Tenant</button>
			    }else 
			    {
				    <h4 class="pb-2">Your subscription plan has been updated to @ViewBag.Subscription . <br> You may now return to your account.</h4>
				    <!-- Button trigger modal -->
				   <a asp-action="Index" asp-controller="Home" class="btn btn-3 ">Return to Account</a>
 
			    }
	    
	    </div>
 </div>

	<!---Popup Form to create tenant-->
	<div class="modal fade" id="exampleModal3" tabindex="-1" role="dialog" aria-labelledby="exampleModalTitle3">
		<div class="modal-dialog modal-dialog" role="document">
        
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title"  id="exampleModalTitle3">Create New Tenant </h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<form method="post" asp-controller="Tenant" asp-action="CreateTenant"  asp-route-payId="@ViewBag.PayReqId" asp-route-reference="@ViewBag.reference">
					<div class="modal-body">
							<p class="text-muted pb-2"> @ViewBag.Subscription Account</p>
                        			
						<div class="form-group">
							<label for="tenantName" class="col-form-label">Tenant name *</label>
							<input type="text" id="tenantName" name="tenantName" class="form-control" required/> <!--input box-->
						</div>
						
						<!---Adds the tenant subscription over here--> 
						@if (@ViewBag.Subscription == "Standard")
						{
							<input name="tenantSubscription" value="Standard" hidden />
                       
						}
						else
						{
							<input name="tenantSubscription" value="Premium" hidden />
						}
			
						<div class="form-group">
							<label for="tenantAddress" class="col-form-label">Address *</label>
							<input type="text" id="tenantAddress" name="tenantAddress" class="form-control" required/> <!--input box-->
						</div>
						
						<br>
						<h6 class="modal-title"> Contact details </h6>

						<div class="form-group">
							<label for="tenantEmail" class="col-form-label">Email *</label>
							<input type="email" id="tenantEmail" name="tenantEmail" class="form-control" required/> <!--input box-->
						</div>

						<div class="form-group">
							<label for="tenantNumber" class="col-form-label">Telephone number *</label>
							<input type="text" id="tenantNumber" name="tenantNumber" class="form-control" pattern="^\d{10}$" required/> <!--input box-->
						</div>

						<!---Add the subscription plans here-->
						
						<div asp-validation-summary="All" class="text-danger"></div>

					</div>
					<div class="modal-footer ">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
						<input type="submit" class="btn colors create" value="Create"/> <!--create button-->
					</div>
				</form>
			</div>
		</div>
	</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

BeanBag/Views/Payment/_UpdateFreeSubscription.cshtml
@using BeanBag.Services
@using Microsoft.Identity.Web
@{
   
    Layout = null;
}
@inject ITenantService _tenantService

@{
  //Get the value of the website theme colour here
  var color = _tenantService.GetTenantTheme(User.GetObjectId());
  var logo = _tenantService.GetLogo(User.GetObjectId());
} 
    @if(color == "KellySheen")
    {
      <link rel="stylesheet" href="~/css/kellyGreen.css" />
    }else if(color == "FieryRose")
    {
      <link rel="stylesheet" href="~/css/fieryRose.css" />
    }else if(color == "CornflowerBlue")
    {
      <link rel="stylesheet" href="~/css/cornflowerBlue.css" />
    } 
    else if (color == "PurpleMountainMajesty")
    {
      <link rel="stylesheet" href="~/css/purpleMountainMajesty.css" />
    }
    else if(color=="OutrageousOrange"){
      <link rel="stylesheet" href="~/css/outrageousOrange.css" />
    }
    else if(color=="Default")
    {
      <link rel="stylesheet" href="~/css/default.css" />
    }
    else
    {
      <link rel="stylesheet" href="~/css/default.css" />
    }
	<!---Popup Form to payment free -->
	<div class="modal fade" id="exampleModal" data-toggle="modal" data-target="#exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalTitle" aria-hidden="true">
		<div class="modal-dialog modal-dialog" role="document">

			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalTitle2">Updated to Free Plan</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="p-3">
					<div >
						<h6 class="pb-4 ">Free Plan</h6>
						Your subscription plan has been successfully updated to a free plan.
					</div> <!-- End -->

					<a class="btn btn-3 shadow-sm bg-body rounded float-right" asp-area="MicrosoftIdentity" asp-controller="Payment" asp-action="Billing">
						OK
					</a>
				</div>

			</div>
		</div>
	</div>

BeanBag/Views/Payment/_UpdatePremiumSubscripition.cshtml
@{
   
    Layout = null;
}
<!---Popup Form to payment premium -->
	<div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalTitle" aria-hidden="true">
		<div class="modal-dialog modal-dialog" role="document">
        
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title"  id="exampleModalTitle2">Payment</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="p-3">
					<div >
						<h6 class="pb-4 ">Premium Plan</h6>
              
					
					</div> <!-- End -->
                    
					<!-- Paypal info -->
					<div  class="tab-pane  pt-1">
						<!--Pay-fast checkout-->
				
				                      
						<div >
							<form action="https://secure.paygate.co.za/payweb3/process.trans" method="POST">
								<!--Email nb-->
							
								<div class="form-group">
									<p class="text-muted"> Please enter your email. This is required for payment confirmation purposes. </p>
                                                            				
									<label class="col-form-label">Email *</label>
									<input type="text" id="email2" name="EMAIL" class="form-control"/> <!--input box-->
								</div>
								<div hidden>
									<input id="PAY_REQUEST_ID2" name="PAY_REQUEST_ID" type="hidden"/>
									<input id="CHECKSUM2" name="CHECKSUM" type="hidden"/>
									<input id="REDIRECT2" type="submit" /></div>
								<div asp-validation-summary="All" class="text-danger"></div>
							
							</form>
						</div>
						<button class="btn btn-outline-light shadow-sm bg-body create rounded colors pb-2"  id="btn-pay2" >Proceed to payment</button> 
                    				
						<ul class="text-info pt-1 " id="results2"></ul>
                                  

					</div> <!-- End -->
					<DIV class="pt-1">
				
						<p class="text-muted"> Note: After clicking on the button, you will be directed to a secure gateway for payment. After completing the payment process, you will be redirected back to the website to view details of your order. </p>
					</DIV>   	
					<img width="150" class="pb-2" src="~/images/payfastlogo.png" alt=""/>
				</div>
			
	
			</div>
		</div>
	</div>
	
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript">
//For premium payment - Get Request
    $('#btn-pay2').on('click', function () {
        let node = document.createElement("li");
        node.innerText = "Processing...";
        document.querySelector("#results2").appendChild(node);

         $.get(`/payment/getrequest`, {email : $('#email2').val(), amount: "100000" })
                    .done(data => success2(data))
                    .fail(err => error2(err));
    });
    
     function success2(data) {
            let requestNode = document.createElement("li");
            requestNode.innerText = "Request retrieved";
            document.querySelector("#results2").appendChild(requestNode);
    
            requestNode.innerText = data.message;
            if (data.success) {
                $("#PAY_REQUEST_ID2").val(data.results.PAY_REQUEST_ID);
                $("#CHECKSUM2").val(data.results.CHECKSUM);
    
    
                let redirectNode = document.createElement("li");
                redirectNode.innerText = "Redirecting...";
                document.querySelector("#results2").appendChild(redirectNode);
    
                document.querySelector("#REDIRECT2").click();
            }
        }
           
    function error2(data) {
        console.log("Error");
        let node = document.createElement("li");
        node.innerText = data;
        document.querySelector("#results2").appendChild(node);
    }  
</script>

BeanBag/Views/Payment/_UpdatePremiumSubscription.cshtml
@using BeanBag.Services
@using Microsoft.Identity.Web
@{
   
    Layout = null;
}



@inject ITenantService _tenantService

@{
  //Get the value of the website theme colour here
  var color = _tenantService.GetTenantTheme(User.GetObjectId());
  var logo = _tenantService.GetLogo(User.GetObjectId());
} 
    @if(color == "KellySheen")
    {
      <link rel="stylesheet" href="~/css/kellyGreen.css" />
    }else if(color == "FieryRose")
    {
      <link rel="stylesheet" href="~/css/fieryRose.css" />
    }else if(color == "CornflowerBlue")
    {
      <link rel="stylesheet" href="~/css/cornflowerBlue.css" />
    } 
    else if (color == "PurpleMountainMajesty")
    {
      <link rel="stylesheet" href="~/css/purpleMountainMajesty.css" />
    }
    else if(color=="OutrageousOrange"){
      <link rel="stylesheet" href="~/css/outrageousOrange.css" />
    }
    else if(color=="Default")
    {
      <link rel="stylesheet" href="~/css/default.css" />
    }
    else
    {
      <link rel="stylesheet" href="~/css/default.css" />
    }

	<!---Popup Form to payment premium -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog" role="document">
        
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title"  id="exampleModalTitle2">Contact Us</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="pt-3 pb-3">
				<div >
					<h6 class="pl-3" >Enterprise Plan</h6>
              
					
				</div> <!-- End -->
                    	</div>
				<!-- Paypal info -->
					<!--Pay-fast checkout-->
				<div class="modal-body pt-2">
					For an enterprise subscription plan, email us at <b>info@agilebridge.co.za</b> 
					and we will be sure to get back to you.</div>
				
				  <div class="modal-footer ">
					  <button type="button" class="btn btn-secondary" data-dismiss="modal">OK</button>
				  </div>
                   					                   
				<!--	<div >
						<form action="https://secure.paygate.co.za/payweb3/process.trans" method="POST">
				
							
							<div class="form-group">
								<p class="text-muted"> Please enter your email. This is required for payment confirmation purposes. </p>
                                                            				
								<label class="col-form-label">Email *</label>
								<input type="text" id="email2" name="EMAIL" class="form-control"/>
							</div>
							<div hidden>
							<input id="PAY_REQUEST_ID2" name="PAY_REQUEST_ID" type="hidden"/>
							<input id="CHECKSUM2" name="CHECKSUM" type="hidden"/>
							<input id="REDIRECT2" type="submit" /></div>
							<div asp-validation-summary="All" class="text-danger"></div>
							
						</form>
					</div>
						<button class="btn btn-outline-light shadow-sm bg-body create rounded colors pb-2"  id="btn-pay2" >Proceed to payment</button> 
                    				
                    					<ul class="text-info pt-1 " id="results2"></ul>
                                  

				</div>
				<DIV class="pt-1">
				
					<p class="text-muted"> Note: After clicking on the button, you will be directed to a secure gateway for payment. After completing the payment process, you will be redirected back to the website to view details of your order. </p>
				</DIV>   	
					<img width="150" class="pb-2" src="~/images/payfastlogo.png" alt=""/>
			</div>-->
			
	
		</div>
		</div>
</div>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript">
//For premium payment - Get Request
    $('#btn-pay2').on('click', function () {
        let node = document.createElement("li");
        node.innerText = "Processing...";
        document.querySelector("#results2").appendChild(node);

         $.get(`/payment/getrequest`, {email : $('#email2').val(), amount: "100000" })
                    .done(data => success2(data))
                    .fail(err => error2(err));
    });
    
     function success2(data) {
            let requestNode = document.createElement("li");
            requestNode.innerText = "Request retrieved";
            document.querySelector("#results2").appendChild(requestNode);
    
            requestNode.innerText = data.message;
            if (data.success) {
                $("#PAY_REQUEST_ID2").val(data.results.PAY_REQUEST_ID);
                $("#CHECKSUM2").val(data.results.CHECKSUM);
    
    
                let redirectNode = document.createElement("li");
                redirectNode.innerText = "Redirecting...";
                document.querySelector("#results2").appendChild(redirectNode);
    
                document.querySelector("#REDIRECT2").click();
            }
        }
           
    function error2(data) {
        console.log("Error");
        let node = document.createElement("li");
        node.innerText = data;
        document.querySelector("#results2").appendChild(node);
    }  
</script>