BeanBag/Controllers/TenantController.cs
using System;
using System.Linq;
using BeanBag.Models;
using BeanBag.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Web;
using X.PagedList;

namespace BeanBag.Controllers
{
    /* This controller is used to send and retrieve data to the account
    view using tenant service and inventory service functions. */
    public class TenantController : Controller
    {
        // Global variables needed for calling the service classes.
        private readonly ITenantService _tenantService;
        private readonly IInventoryService _inventory;
        private readonly IPaymentService _paymentService;

        // Constructor.
        public TenantController(ITenantService tenantService, IInventoryService inventory, IPaymentService paymentService)
        {
            _tenantService = tenantService;
            _inventory = inventory;
            _paymentService = paymentService;
        }

        /* This function adds a page parameter, a current sort order parameter, and a current filter
        parameter to the method signature and returns the Tenant Index page view. */
         [AllowAnonymous]
        public IActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            if (User.GetObjectId() == null)
            {
                throw new Exception("User ID is null");
            }
            else if (_tenantService.SearchUser(User.GetObjectId()))
            {
                return RedirectToAction("Index", "Home");
            }
            
             //A ViewBag property provides the view with the current sort order, because this must be included in 
             //the paging links in order to keep the sort order the same while paging
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            //ViewBag.CurrentFilter, provides the view with the current filter string.
            //he search string is changed when a value is entered in the text box and the submit button is pressed. In that case, the searchString parameter is not null.
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            var model = from s in _tenantService.GetTenantList()
                select s;
            
                //Search and match data, if search string is not null or empty
                if (!String.IsNullOrEmpty(searchString))
                {
                    model = model.Where(s => s.TenantName.Contains(searchString));
                }

                var tenants = model.ToList();
            
                //Sort card list of tenants alphabetically
                var modelList = tenants.OrderBy(s => s.TenantName).ToList();

                
            //indicates the size of list 4 card items per page
            int pageSize = 3;
            //set page to one is there is no value, ??  is called the null-coalescing operator.
            int pageNumber = (page ?? 1);
            //return the Model data with paged

            Tenant tenant = new Tenant();
            Pagination viewModel = new Pagination();
            IPagedList<Tenant> pagedList = modelList.ToPagedList(pageNumber, pageSize);
            
            viewModel.Tenant = tenant;
            viewModel.PagedListTenants = pagedList;
     
            return View(viewModel);
         
        }
        
        // This function allows a user to create a new tenant.
        [HttpPost]
        public IActionResult CreateTenant(string tenantName, string tenantAddress,
            string tenantEmail, string tenantNumber, string tenantSubscription, string reference, string payId)
        {
            Console.WriteLine("Checking the user id create tenant: " + User.GetObjectId());

            if (tenantName == null)
            {
                return RedirectToAction("Index");
            }
            var currentTenantId = _tenantService.CreateNewTenant(tenantName, tenantAddress, tenantEmail, tenantNumber,tenantSubscription);

            return SelectTenant(currentTenantId,reference,payId);
        }

        /* This function allows a user to select a tenant and generates
         a new user inventory for demonstration purposes*/
        public IActionResult SelectTenant(string tenant, string reference, string payId)
        {
            if (tenant == null)
            {
                return RedirectToAction("Index");
            }

            //Check if user is new
            var userId = User.GetObjectId();
            var currentTenantId = tenant;
            var userName = "";
            
            if (User.Identity != null)
            {
                userName = User.Identity.Name;
            }
            
            if (_tenantService.SearchUser(userId) == false)
            {
                //User is new - add user to database
                //Verify tenant
                if (_tenantService.SearchTenant(currentTenantId))
                {
                    //Verified
                    if (userName != null)
                    {
                        _tenantService.SignUserUp(User.GetObjectId(), currentTenantId, userName);
                        _tenantService.EditUserRole(User.GetObjectId(), "Admin");
                    }
                    else
                    {

                        _tenantService.SignUserUp(User.GetObjectId(), currentTenantId, "");
                    }

                    //confirm transaction
                    
                        if (_tenantService.GetCurrentTenant(userId).TenantSubscription.Equals("Standard"))
                        {
                             double amount = 500;
                            //Add the transaction to the DB 
                            _paymentService.AddTransaction(reference, payId, currentTenantId, amount);
                        }
                    
                }
                else
                {
                    throw new Exception("Tenant does not exist");
                }
            }

            //New inventory created for first time user.
            Inventory newInventory = new Inventory()
            {
                name = "My First Inventory",
                userId = userId,
                description = "My first ever inventory to add new items to",
                createdDate = DateTime.Now
            };
            _inventory.CreateInventory(newInventory);
            
            //logo for first time user 
     
            return RedirectToAction("Index", "Home");
        }
    }
}

BeanBag/Controllers/WelcomeController.cs
using System;
using BeanBag.Database;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using BeanBag.Services;
using Microsoft.Identity.Web;

namespace BeanBag.Controllers
{
    public class WelcomeController : Controller
    {

        private readonly ITenantService _tenantService;
        private readonly TenantDbContext _tenantDbContext;
        public WelcomeController(ITenantService tenantService, TenantDbContext context)
        {
            _tenantService = tenantService;
            _tenantDbContext = context;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            if (User.GetObjectId() == null)
            {
                throw new Exception("User ID is null");
            }
            else if (_tenantService.SearchUser(User.GetObjectId()))
            {
                //Redirect user to dashboard if they are already signed up
                return RedirectToAction("Index", "Home");
            }
            
            return View();
        }

        
        /* Receives invitation code and verifies if the code is correct.
         If correct the user is signed up and gets redirected to the dashboard */
        [HttpPost]
        public IActionResult VerifyCode(string code)
        {
            if (code == null)
            {
                return BadRequest();
            }

            //Verify the entered code
            if (_tenantService.VerifyCode(code))
            {
                //Code is verified, sign user up under tenant 
                var tenant = _tenantService.GetInvitationTenant(code);

                if (tenant == null)
                {
                    return BadRequest();
                }

                //Add user to the database
                if (_tenantService.SignUserUp(User.GetObjectId(), tenant.TenantId, User.GetDisplayName()))
                {
                   /* tenant.InviteCode = _tenantService.GenerateCode();
                    _tenantDbContext.SaveChanges(); */
                    return RedirectToAction("Index", "Home");
                }

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

    }
}

BeanBag/Views/Welcome/Index.cshtml
@{
   
    Layout = null;
}
<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Bootstrap CSS -->

	<link rel = "icon" href ="https://img.icons8.com/ios/50/ffffff/circled-b.png" type = "image/x-icon">
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta/css/bootstrap.min.css" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" rel="stylesheet">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link rel="stylesheet" href="~/css/dashboard.css" />
	<link rel="stylesheet" href="~/css/tenant.css" />
  
	<title> Welcome </title>

</head>


<style>
    .hidden {
        display: none;
    }

    li {
        list-style-type: none;
    }
 
</style>



<!--Nav-->
<nav class="navbar navbar-expand-md navbar-light">
	<a href="#" class="navbar-brand">Bean Bag</a>
	 <button class="navbar-toggler ml-auto float-right mr-5" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		 <span class="navbar-toggler-icon"></span>
	</button>
	
	
	<div class="collapse navbar-collapse float-right ml-sm-auto"  id="navbarNav" >
		<ul class="navbar-nav ml-auto  pt-1">
				
			<li class="nav-item mr-5">

			

				<a class="nav-link  float-right active" asp-area="MicrosoftIdentity" asp-controller="Welcome" asp-action="Index">
					Home
				</a>


			</li>
			
			<li class="nav-item  mr-5 ">		<a class="nav-link float-right" asp-area="MicrosoftIdentity" asp-controller="Tenant" asp-action="Index">
                                                    					Plans
                                                    				</a>
                        		</li>
			<li class="nav-item  mr-5 ">
				<a class="nav-link float-right" asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignOut">
					SignOut
				</a>
			</li>

		</ul>
		
	</div>
		<hr>
</nav>

<div class="container pl-3 pr-3 h-75 d-flex justify-content-center">
    <div class=" my-auto pt-xl-3 pl-3 pr-3 text-center">    
	    <!--Successful Payment here-->
	    <h1> Welcome to Bean Bag </h1>
	    <h5 > Begin by joining or creating <br>
		    a new tenant</h5>
        	<h4 class="pb-2"></h4>
	    
	    <!-- Button to go to create tenant page -->
	    <a class="btn btn-outline-light shadow-sm bg-body create rounded colors pt-2 " id="btn-create"
	            asp-action="Index" asp-controller="Tenant">Create Tenant</a>
	    
	    <!-- Button to enter invitation code -->
	    <a asp-controller="Welcome" asp-action="VerifyCode" class="btn btn-outline-light shadow-sm bg-body create rounded colors pt-2 " 
                    data-toggle="modal" data-target="#exampleModalCode">Join Tenant</a>
            			                                                                                                                                            
           
    </div>
 </div>

	<!---Popup Form to create tenant-->
	<div class="modal fade" id="exampleModalCode" tabindex="-1" role="dialog" aria-labelledby="exampleModalTitleCode">
		<div class="modal-dialog modal-dialog" role="document">
        
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title"  id="exampleModalTitleCode">Invitation Code</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<form method="post" asp-controller="Welcome" asp-action="VerifyCode">
					<div class="modal-body">
							<p class="text-muted pb-2">Enter an invitation code below to gain access to an already existing tenant.</p>
                        			
						<div class="form-group">
							<label for="code" class="col-form-label">Invitation Code:</label>
							<input type="text" id="code" name="code" class="form-control"/>
						</div>
						
						
						<div asp-validation-summary="All" class="text-danger"></div>

					</div>
					<div class="modal-footer ">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
						<input type="submit" class="btn colors create" value="Verify Code"/> <!--create button-->
					</div>
				</form>
			</div>
		</div>
	</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>